apiVersion: v1
kind: Service
metadata:
  name: api-orders-service
spec:
  selector:
    app: api-orders
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31003
  type: LoadBalancer
